### ISSUE TITLE
Upgrade to Kamon 1.0

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-statsd#1]
I just realized that we don't have an issue to track this, so, here it is.

**Comment by subourbonite** [comment]
Is there a timeline for this? We make heavy use of kamon-statsd, and would like to be able to upgrade to 1.0. I would be willing to take on some of this work if necessary.

**Comment by ivantopo** [comment]
hey @briggsw, we actually have two PRs open with this! See https://github.com/kamon-io/kamon-statsd/pull/2 and https://github.com/kamon-io/kamon-statsd/pull/3, would you like to help with the review and feedback to get https://github.com/kamon-io/kamon-statsd/pull/2 merged?

**Comment by Vinh-Vu-ck** [comment]
hey @ivantopo, what's the status on this? I read here [#2](https://github.com/kamon-io/kamon-statsd/pull/2) that it was supposed to be released last weekend? Also, will this upgrade include support for Akka 2.5? Looking forward to the upgrade! :)

**Comment by acjay** [comment]
_Seems_ like with #2 merged, as new release may simply need to be published.

**Comment by ivantopo** [comment]
Finally managed to publish this as 1.0.0! Thanks a lot to alessandrosimi-sa for the effort :D
