### ISSUE TITLE
Versioning up to 2.x.x

### ISSUE THREAD

**Issue by cosmir17** [kamon-io/kamon-statsd#7]
I would like to use Statsd with other Kamon 2.x.x dependencies.
Can you upgrade this project to Kamon 2.x.x, please?

**Comment by kvma** [comment]
this appears to be in the works by xeppaka (thanks Pavel!) 
https://github.com/kamon-io/kamon-statsd/pull/8

**Comment by cosmir17** [comment]
@kvma @xeppaka Thank you 👍

**Comment by ivantopo** [comment]
Version [2.0.0](https://github.com/kamon-io/kamon-statsd/releases/tag/v2.0.0) was released last week, closing this one!
