### ISSUE TITLE
Scala 2.13 compatibility

### ISSUE THREAD

**Issue by TimSoethout** [kamon-io/kamon-statsd#9]
I'm upgrading my project, but kamon-statsd is holding me back now.

I guess this is related to https://github.com/kamon-io/kamon-statsd/pull/8. Maybe 2.13 can be added as well?

**Comment by khrupalyk** [comment]
HI @TimSoethout! What problem do you have?  I tested on 2.13.1, all looks good.

**Comment by markusthoemmes** [comment]
Is it possible for us to cut a new release and/or push a 2.13 compatible artifact?

**Comment by ivantopo** [comment]
Hey folks.. I have been wanting to release this for a few days now but honestly, I didn't get the chance to fully review it and tomorrow I'm going away for a conference for a few days. I'll try my best to properly review it and publish as soon as possible!

**Comment by ivantopo** [comment]
Released last week as 2.0.0!
